export enum agentTypes {
    FETCH_AGENTS = "FETCH_AGENTS",
    FETCH_AGENTS_SUCCESS = "FETCH_AGENTS_SUCCESS",
    FETCH_AGENTS_FAILURE = "FETCH_AGENTS_FAILURE",
    FETCH_AGENT_BYID = "FETCH_AGENT_BYID",
    FETCH_AGENT_BYID_SUCCESS = "FETCH_AGENTS_SUCCESS_BYID",
    FETCH_AGENT_BYID_FAILURE = "FETCH_AGENTS_FAILURE_BYID",
}